### ISSUE TITLE
Cannot Find Code

### ISSUE THREAD

**Issue by cdb8457** [mov3ax/airdrop#1]
override void OnUpdate( float timeslice )

I might be blind, but cannot find this in the default ini

**Comment by lonewolfss** [comment]
i am having problems also this dose not work i found where to put the override void OnUpdate( float timeslice ) 
and the plane dose not work i even put it to 3 min timer also enabled and still nothing 

`bool PrintDebugMessages = true; // Show debug messages (Debug)
	bool DropOnStart = false; // Drop airdrop instantly after airplane (Debug)
	bool TeleportDebug = true; // Teleport to airplane and airdrop during flight (Debug)`

`override void OnUpdate(float timeslice)
	{
		UpdateDummyScheduler();
		TickScheduler(timeslice);
		UpdateLogoutPlayers();
                super.OnUpdate( timeslice );		
	}`

**Comment by lonewolfss** [comment]
lol so much on the confusing side lol i think the guide needs to be adjusted for anyone having problems dont look in init.c for the last step you need to go to the link below and the file you need is in there  after that was corrected it worked perfect for me great work
dta\scripts\5_mission\mission\missionServer.c

**Comment by mov3ax** [comment]
My bad, there is no default "OnUpdate" method. Just add it to your init.c

```
float TimerSlice;
	override void OnUpdate( float timeslice )
	{
		super.OnUpdate( timeslice );

		// FPS Fix
		TimerSlice += timeslice;
		if (TimerSlice >= TimesliceMultiplyier)
		{
			CreateAirDrop();
			TimerSlice = 0;	
		}
	}
```
