### ISSUE TITLE
Fix items

### ISSUE THREAD

**Issue by Corpulio** [mov3ax/airdrop#11]
Hi,

I use your airdrop and its awesome!!! But i have a question. How can i put in fix items not random items? Can u help me? Thank you!
B.

**Comment by mov3ax** [comment]
You mean you wan't to put fixed items, like airdrop will have same items anytime?

**Comment by Corpulio** [comment]
Yes i want fixed items anytime.

**Comment by mov3ax** [comment]
https://github.com/mov3ax/airdrop/blob/new/plugins/AirDrop.c#L299-L304 

put there loot name you wan't instead of GetRandomLoot()

e.g 

m_AirDropLoot.GetInventory().CreateInInventory("M4A1");

**Comment by Corpulio** [comment]
Thank you! I will try it! Awesome work! 😉
