### ISSUE TITLE
Can I ask what was updated

### ISSUE THREAD

**Issue by exm316** [mov3ax/airdrop#12]
Hello,

I have the airdrops working fine (well kinda), and I'm wondering what was updated in the last update?

I currently have to have the drops set to DropOnStart so that I can get repeat drops every 30mins, but no Flare or Landmine effects even though set to = true.

**Comment by mov3ax** [comment]
https://github.com/mov3ax/airdrop/commit/2b18d82acd7f5b99c0c5f710bc297c76abcfa904

It's currently don't work on server-side at all

**Comment by S4MT3K** [comment]
> 
> 
> [2b18d82](https://github.com/mov3ax/airdrop/commit/2b18d82acd7f5b99c0c5f710bc297c76abcfa904)
> 
> It's currently don't work on server-side at all

do you figured out what it is? Im searching the whole code right now to look if theres something diffrent between my local started server and the server in the "cloud/Online" till yet i found nothing. i also searched the procedures and tasks in taskmanager and tried to compare them. IMO this has maybe something to do with private and public access of the classes and ultimately with the access of the particle system. Just an idea. Hope this point of view is helpful... Greetz S4MT3K

**Comment by mov3ax** [comment]
https://github.com/mov3ax/airdrop/commit/6230941f13558aa3d57b2dc659e93e93b0e30023 fixed
