### ISSUE TITLE
Drop in the middle of the ocean

### ISSUE THREAD

**Issue by Wizbaggd** [mov3ax/airdrop#2]
![image](https://user-images.githubusercontent.com/37152977/46477978-8920c380-c81e-11e8-8e85-17c79e7e1f54.png)

I don't think you intended these to drop in the middle of the ocean. Coords were 2700, 0, 67 - As you see in the picture, that places it south of Prison Island in the middle of the ocean.

**Comment by Diesel42o** [comment]
I am also getting it dropping in the ocean

**Comment by lonewolfss** [comment]
i have set custom spawn points for anyone who needs them i will post below for you all 

`// Generating random airdrop position from list
	// You can get coordinates using debug monitor or this map https://dayz.ginfo.gg/
	vector GetAirPlanePos() 
	{
		protected vector airplane_yaw; // Local variable
		airplane_yaw[1] = AirPlaneHeight; // Airplane fly height 
		
		switch (Math.RandomInt(0, 12)) {
		//Balota Airfeild//	
		case 0:
		airplane_yaw[0] = 4965.45;
		airplane_yaw[2] = 2515.47;
		break;
		// Berezino //
		case 1:
		airplane_yaw[0] = 12287.3;
		airplane_yaw[2] = 8471.17;
		break;
		//Guglovo//
		case 2:
		airplane_yaw[0] = 8402.09;
		airplane_yaw[2] = 6852.75;
		break;
		//Kemenka//
		case 3:
		airplane_yaw[0] = 1047.04;
		airplane_yaw[2] = 2268.01;
		break;
		//Krasnostav//
		case 4:
		airplane_yaw[0] = 11764.1;
		airplane_yaw[2] = 12147.6;
		break;
		//Pusta//
		case 5:
		airplane_yaw[0] = 9200.91;
		airplane_yaw[2] = 3983.34;
		break;
		//Solnichny//
		case 6:
		airplane_yaw[0] = 13401.9;
		airplane_yaw[2] = 5995.73;
		break;
		//Vyshnoye//
		case 7:
		airplane_yaw[0] = 6570.06;
		airplane_yaw[2] = 6097.29;
		break;
		//ELECTRO//
		case 8:
		airplane_yaw[0] = 9963.12;
		airplane_yaw[2] = 1773.89;
		break;
		//Guglovo//
		case 9:
		airplane_yaw[0] = 8380.97;
		airplane_yaw[2] = 6546.03;
		break;
		//GreenMountain
		case 10:
		airplane_yaw[0] = 3907.36;
		airplane_yaw[2] = 5853.72;
		break;
		//VMC
		case 11:
		airplane_yaw[0] = 4886.02;
		airplane_yaw[2] = 8153.1;
		break;
		//Novy
		case 12:
		airplane_yaw[0] = 7353.07;
		airplane_yaw[2] = 7656.14;
		break;
		}
		
		return airplane_yaw;
	}`

**Comment by mov3ax** [comment]
`RandomTime = Math.RandomFloat(75 / TimesliceMultiplyier, 180 / TimesliceMultiplyier); // Random drop bounds`

Increase this value and adjust it to your coordinates
