### ISSUE TITLE
Log's flood when server was empty during airdrop

### ISSUE THREAD

**Issue by elanc** [mov3ax/airdrop#3]
NULL pointer to instance
Class:      'CustomMission'
Function: 'SpawnAirPlaneAndMove_DEBUG'
Stack trace:
mpmissions\dayzOffline.chernarusplus\init.c:249
mpmissions\dayzOffline.chernarusplus\init.c:384
mpmissions\dayzOffline.chernarusplus\init.c:434
scripts/3_Game/dayzgame.c:1633

249: protected vector m_OldAirDropPos = m_AirDrop.GetPosition();
384: SpawnAirPlaneAndMove_DEBUG();
434: CreateAirDrop();

**Comment by mov3ax** [comment]
Fixed - https://github.com/mov3ax/airdrop/commit/d193bc844e4815b9d9c10d2a776f98b6a4a9b04b
