### ISSUE TITLE
it doesnt work

### ISSUE THREAD

**Issue by Tualok** [mov3ax/airdrop#6]
SCRIPT    (E): NULL pointer to instance. Variable 'TimesliceMultiplyier'
Class:      'CustomMission'
Function: 'CustomMission'
Stack trace:
mpmissions\dayzOffline.chernarusplus\init.c:32
mpmissions\dayzOffline.chernarusplus\init.c:110

this version of the AirDrop doesnt work i dont no why

**Comment by mov3ax** [comment]
give me your code in 32 and 110 line in your init.c

**Comment by Tualok** [comment]
32: class CustomMission: MissionServer
100: 	return new CustomMission();

i have installed it with your youtube tutorial but the airdrop doesn´t worked

**Comment by mov3ax** [comment]
I fixed and explained it there - https://github.com/mov3ax/airdrop/commit/5b2c2517a1c129129f0b32e074c2c6e23eda0bfe 

check if it will work and andswer, ill close the issue

**Comment by Tualok** [comment]
thank you now it works
