### ISSUE TITLE
smoke doesn´t work

### ISSUE THREAD

**Issue by Tualok** [mov3ax/airdrop#7]
Hello,

i have enabled the smoke signal at the Airdrop but there is no smoke.

**Comment by mov3ax** [comment]
Hi, smoke appears after the airdrop landed on the ground, did you change the code?

**Comment by Tualok** [comment]
bool ShowSignal = true; // Show smoke signal when airdrop landed
when the drop is landed there is no smoke i have tested it many times no smoke

**Comment by mov3ax** [comment]
![image](https://user-images.githubusercontent.com/35667100/46585715-b8cd0700-ca7c-11e8-940d-8aa642f95165.png)
most likely you make a mistake somewhere

**Comment by Tualok** [comment]
i have changed nothing just enable the smoke bool ShowSignal = true; // Show smoke signal when airdrop landed

**Comment by S4MT3K** [comment]
Just want to let you know that the same thing is happen here. No particle effects at all. Not even the Landmine thing.

**Comment by fabienthomas** [comment]
Hi, same here, no effect at all, checked the code several times, rest works good, thanks a lot !

**Comment by mov3ax** [comment]
For example, does a spawn zombie work for you fine?

**Comment by Tualok** [comment]
zombies are working fine

**Comment by S4MT3K** [comment]
I agree. Zombies are Working.

**Comment by exm316** [comment]
Same issue..... Zombies work but no smoke effect or Landmine effects!

I also I have it set to start after 3 mins, clear after 15 mins (only for test purposes) - the first drop occurs but after it is cleared up and the next plane fly's out no drop happens?

**Comment by S4MT3K** [comment]
Search the other issue. I „fixed“ it temporally 😂.
Not really. Im not that good. But when you turn on DropOnStart, it works. For now. I hope there will be a update

**Comment by fabienthomas** [comment]
Yes, Zombies are working fine 
And like @exm316 said, i have the first drop 2 mintutes after servar start (TicksTimerFromStart = 120), but nothing more after, the container is removed on correct time (RemoveTime = 130), but no other airdrop after.

**Comment by S4MT3K** [comment]
UPDATE: 
I played a bit around with the spawnpoints. We also tryed to figure out if the Physics is working. And i figured out that even this isnt working for me. Tryed to let them drop on roofs and trees. i also tooked a new one (untouched code) and even this isnt working. so the physics are broken aswell.. #info

**Comment by mov3ax** [comment]
Figured out that, there is some bug, in offline mode drop effect and smoke works but in server they don't work, now i'm looking for possible fix

**Comment by mov3ax** [comment]
https://github.com/mov3ax/airdrop/commit/2b18d82acd7f5b99c0c5f710bc297c76abcfa904 - will be fixed when possible
