### ISSUE TITLE
plane wont drop more than 1 drop

### ISSUE THREAD

**Issue by lonewolfss** [mov3ax/airdrop#8]
updated to new update put a test on for the drops 1st plane enters drops container and then cleans up 2nd plane comes no container.
no smoke or effects either not changed any code for the airdrops only added in cords for drops and set the timers i have the following files  

Dayzserver\mpmissions\dayzOffline.chernarusplus\plugins\ AirDrop.c

`class AirDrop
{
	/* ### ### ### ### ### ### ### ### */
	/* DayZ 0.63 AirDrop plugin by mov3ax / mov3ax.pro */
	/* ### ### ### ### ### ### ### ### */	

	void AirDrop()
	{
	}

	void ~AirDrop()
	{
	}

	/* ### ### ### ### ### ### ### ### */
	/* Configuration of plugin */
	/* ### ### ### ### ### ### ### ### */

	bool EnableAirdrops = true; // Main switch
	float TimesliceMultiplyier = 0.01; // Timeslice multiplyier, default value is 0.01 (60 FPS)
	float AirPlaneSpeed = 0.23; // Airplane fly speed 
	float AirPlaneHeight = 275; // Airplane fly height 
	// 600 Seconds = 10 Minutes
	float TicksTimerFromStart = 30  / TimesliceMultiplyier; // How much time will pass from the server start to first airdrop
	bool PrintInformationMessages = true; // Show in chat when airplane flew out and when airdrop is landed
	bool PrintInformationCoordinates = true; // Show in chat coordinates where airdrop is landed
	// 36000 Seconds = 1 Hour
	float RemoveTime = 60 / TimesliceMultiplyier; // After how much time airplane and loot will be removed and new airplane will be spawned
	bool SpawnZombie = true; // Spawn zombie near airdrop when landed
	bool ShowSignal = true; // Show smoke signal when airdrop landed
	float RandomBoundsMin = 95; // Airdrop drop bounds min
	float RandomBoundsMax = 180; // Airdrop drop bounds max
	bool PrintDebugMessages = false; // Show debug messages (Debug)
	bool DropOnStart = false; // Drop airdrop instantly after airplane (Debug)
	bool TeleportDebug = false; // Teleport to airplane and airdrop during flight (Debug)

	/* ### ### ### ### ### ### ### ### */
	/* Local variables */
	/* ### ### ### ### ### ### ### ### */

	vector m_AirPlaneFixedPosition; // Local variable
	vector m_DropPos; // Local variable

	Object m_AirPlane; // Global airplane object
	Object m_AirDrop; // Glbal airdrop container object
	Object m_Platform; // Glbal airdrop container object

	EntityAI m_AirDropLoot; // Airdrop container body
	ItemBase m_AirDropBase; // Airdrop container base

	Particle DropEffect; // Airdrop land particle effect	
	Particle SignalEffect; // Airdrop land particle effect	

	vector RandomRotOrientation; // Local variable	
	EntityAI PhysicsBody; // Local variable

	float RandomRot = 0; // Default random rotation variable
	float RandomTime = 100; // Default random drop variable
	float Delay = 0; // Local variable for security
	float Ground; // Local variable for security

	int AirDropTime = 0; // Local variable
	int AirTimer = 0; // Local variable
	int RemoveTimer = 0; // Local variable

	bool RayReady = true; // Local variable
	bool TimerPassed = false; // Local variable
	bool AirPassed = false; // Local variable
	bool RemovePased = false; // Local variable
	bool DropTime = false; // Local variable
	bool PassTime = false; // Local variable

	/* ### ### ### ### ### ### ### ### */
	/* Global functions */
	/* ### ### ### ### ### ### ### ### */

	// Send message in global chat
	void SendMessage(string message) 
	{
		ref array<Man> players = new array<Man>; 
		GetGame().GetPlayers( players ); 
		
		for ( int i = 0; i < players.Count(); i++ ) 
		{ 
			PlayerBase player1; 
			Class.CastTo(player1, players.Get(i)); 

			Param1<string> m_AirTimer = new Param1<string>(message); 
			GetGame().RPCSingleParam(player1, ERPCs.RPC_USER_ACTION_MESSAGE, m_AirTimer, true, player1.GetIdentity()); 
		}
	}
	
	// Teleport all players to position, debug
	void SendPos(vector pos) 
	{
		ref array<Man> players = new array<Man>; 
		GetGame().GetPlayers( players ); 
		
		for ( int i = 0; i < players.Count(); i++ ) 
		{ 
			PlayerBase player1; 
			Class.CastTo(player1, players.Get(i)); 

			player1.SetPosition(pos);
		}
	}

	/* ### ### ### ### ### ### ### ### */
	/* Configuration of loot and spawn points */
	/* ### ### ### ### ### ### ### ### */

	// Random Loot Presets
	string GetRandomLoot() 
	{
		TStringArray loot = {
		"LandMineTrap", 
		"TTSKOPants", 
		"TacticalBaconCan", 
		"M4A1", 
		"PlateCarrierComplete", 
		"BakedBeansCan", 
		"WaterBottle", 
		"Mag_AKM_Drum75Rnd",
		"GhilleAtt_Mossy",
		"GhillieSuit_Mossy",
		"GhillieHood_Mossy",
		"Battery9V",
		"BaseRadio",
		"BurlapSack",
		"Lockpick",
		"SmallProtectorCase",
		"Netting",
		"RocketAviators",
		"Binoculars",
		"TacticalGloves_Black",
		"HuntingKnife",
		"Shovel",
		"DuctTape",
		"DallasMask",
		"HoxtonMask",
		"BalaclavaMask_Blackskull",
		"BalaclavaMask_Black",
		"BalaclavaMask_Green",
		"BalaclavaMask_Blue",
		"HighCapacityVest_Olive",
		"HighCapacityVest_Black",
		"Mag_FNX45_15Rnd",
		"Mag_CZ75_15Rnd",
		"Mag_MP5_30Rnd",
		"Mag_UMP_25Rnd",
		"Mag_SVD_10Rnd",
		"KobraOptic",
		"PistolSuppressor",
		"AK_Suppressor",
		"Mag_STANAG_30Rnd",
		"M4_Suppressor",
		"Mag_AKM_30Rnd",
		"PUScopeOptic",
		"BandageDressing",
		"StartKitIV",
		"SalineBag",
		"AmmoBox",
		"AmmoBox_380_35rnd",
		"AmmoBox_45ACP_25rnd",
		"AmmoBox_556x45_20Rnd",
		"AmmoBox_762x39_20Rnd",
		"AmmoBox_762x54_20Rnd",
		"AmmoBox_9x19_25rnd",
		"Ammo_45ACP",
		"Ammo_556x45",
		"Ammo_762x39",
		"Ammo_762x54",
		"AKM",
		"SVD",
		"UMP45",
		"MP5K",
		"MakarovIJ70",
		"FNX45",
		"CZ75",
		"Mp133Shotgun",
		"Izh18",
		"Mosin9130",
		"SawedoffMosin9130",
		"CZ61",
		"Mag_STANAGCoupled_30Rnd",
		"SodaCan_Cola",
		"SodaCan_Kvass",
		"SodaCan_Pipsi",
		"SodaCan_Spite",
		"WaterBottle",
		"Canteen",
		
		};

		return loot.GetRandomElement();
	}
	
	// Generating random airdrop position from list
	// You can get coordinates using debug monitor or this map https://dayz.ginfo.gg/
	vector GetAirPlanePos() 
	{
		TVectorArray positions = { 
        "4965.45 0 2515.47", //Balota Airfeild//
		"5003.16 0 2510.58", //Balota Airfeild//
		
		};

		vector what = positions.GetRandomElement();
		what[1] = AirPlaneHeight;
        return what;
	}

	/* ### ### ### ### ### ### ### ### */
	/* Zombie spawn list */
	/* ### ### ### ### ### ### ### ### */

	TStringArray WorkingZombieClasses()
	{
		return {
		"Animal_CanisLupus_Grey","Animal_CanisLupus_White","Animal_CanisLupus_Grey",	
		"Animal_CanisLupus_Grey","Animal_CanisLupus_White","Animal_CanisLupus_Grey",
		"Animal_CanisLupus_White","Animal_CanisLupus_Grey","Animal_CanisLupus_White",
		"ZmbF_MilkMaidOld_Beige","ZmbF_MilkMaidOld_Black","ZmbF_MilkMaidOld_Green",
		"ZmbF_MilkMaidOld_Grey","ZmbM_priestPopSkinny_Base","ZmbM_priestPopSkinny",
		"ZmbM_ClerkFat_Base","ZmbM_ClerkFat_Brown","ZmbM_ClerkFat_Grey","ZmbM_ClerkFat_Khaki",
		"ZmbM_ClerkFat_White","ZmbF_Clerk_Normal_Base","ZmbF_Clerk_Normal_Blue",
		"ZmbF_Clerk_Normal_White","ZmbF_Clerk_Normal_Green","ZmbF_Clerk_Normal_Red",
		};
	}

	/* ### ### ### ### ### ### ### ### */
	/* Airplane and airdrop setup */
	/* ### ### ### ### ### ### ### ### */

	void GetAirPlaneInfo()
	{
		// Seconds devide on value of TimesliceMultiplyier (By default it is 0.01)
		RandomTime = Math.RandomFloat(RandomBoundsMin / TimesliceMultiplyier, RandomBoundsMax / TimesliceMultiplyier); // Random drop bounds
		RandomRot = Math.RandomFloat(130, 190); // Random rot bounds

		if (PrintDebugMessages)
		SendMessage("[Airdrop, Debug] Random rotation of airplane is " + RandomRot);		
		
		// Dynamic movement forward
        float Forward = RandomRot * 0.017453292;

		// 7.5 is airdrop container motion speed
		float MotionX  = (double)(Math.Sin(Forward) * 7.5); 
        float MotionZ = (double)(Math.Cos(Forward) * 7.5);

		// Fixed position, if we dont multiply value to -1 it will move backwards
		m_AirPlaneFixedPosition[0] = MotionX * -1;
		m_AirPlaneFixedPosition[1] = 10;
		m_AirPlaneFixedPosition[2] = MotionZ * -1;
		RandomRotOrientation[0] = RandomRot;

		m_AirPlane = GetGame().CreateObject( "Land_Wreck_C130J", GetAirPlanePos(), false, true ); // Create airplane model
		m_AirPlane.SetOrientation(RandomRotOrientation); // Rotate it to random angles in yaw

		m_AirPlane.PlaySoundLoop("powerGeneratorLoop", 10000, true); // Attach airplane sound to itself, need to be fixed
		
		if (PrintInformationMessages)
			if (m_AirPlane != NULL)
				SendMessage("Airplane Is Inbound To Drop A Supplie Container, Watch The Sky For The Plane!");	

		m_AirPlane.SetPosition( m_AirPlane.GetPosition() );
		m_DropPos = ( m_AirPlane.GetPosition() ) - m_AirPlaneFixedPosition;

		protected vector pos; pos[0] = 0; pos[1] = AirPlaneHeight; pos[2] = 0;

		m_Platform = GetGame().CreateObject( "Land_Container_1Bo", pos, false, true ); 
		PhysicsBody = EntityAI.Cast( GetGame().CreateObject( "CivilianSedan", m_Platform.GetPosition(), false, true ) );
        PhysicsBody.SetAllowDamage( false );	
	
		if (DropOnStart) // For debug puproses only
		{
			RayReady = false;

			if (PrintInformationMessages)
			SendMessage("Airdrop Container Has Been Deployed Have Fun!!");	

			m_AirDrop = GetGame().CreateObject( "Land_Container_1Bo", m_DropPos, false, true ); // Create airdrop model, in this case it is red container
			
			SetVelocity(PhysicsBody, "10 0 0");
			GetGame().ObjectDelete(m_Platform);
			SetVelocity(PhysicsBody, "10 0 0");

			// Reset it to default values
			RemoveTimer = 0;
			RemovePased = false;
		}

		if (TeleportDebug) // For debug puproses only
		{
			SendPos(m_AirPlane.GetPosition());
		}
	}

	void MoveAirPlane()
	{
		// Dynamic movement forward
        float Forward = RandomRot * 0.017453292;

		// 7.5 is airdrop container motion speed
		float MotionX  = (double)(Math.Sin(Forward) * AirPlaneSpeed); 
        float MotionZ = (double)(Math.Cos(Forward) * AirPlaneSpeed);

		// Fixed position, if we dont multiply value to -1 it will move backwards
		m_AirPlaneFixedPosition[0] = MotionX * -1;
		m_AirPlaneFixedPosition[1] = 0;
		m_AirPlaneFixedPosition[2] = MotionZ * -1;

		m_AirPlane.SetPosition( m_AirPlane.GetPosition() + m_AirPlaneFixedPosition );
		m_DropPos = ( m_AirPlane.GetPosition() ) - m_AirPlaneFixedPosition;

		if (!RayReady)
		{
			Ground = GetGame().SurfaceY(m_AirDrop.GetPosition()[0], m_AirDrop.GetPosition()[2]);
			if (PhysicsBody.GetPosition()[1] <= Ground)
				PhysicsBody.SetVelocity(PhysicsBody, "0 0 0");

			if (GetVelocity(PhysicsBody)[0] < 0.0001 && GetVelocity(PhysicsBody)[1] < 0.0001 && GetVelocity(PhysicsBody)[2] < 0.0001)
			{
				m_AirDrop.PlaceOnSurface();
	
				// Create airdrop lootable container, in this case it is sea chest	
				m_AirDropLoot = EntityAI.Cast(GetGame().CreateObject( "SeaChest", m_AirDrop.GetPosition(), false, true )); // We can't add barrel because it have to be opened
				
				// You can extend items count inside airdrop container or make it random
				m_AirDropLoot.GetInventory().CreateInInventory(GetRandomLoot());
				m_AirDropLoot.GetInventory().CreateInInventory(GetRandomLoot());
				m_AirDropLoot.GetInventory().CreateInInventory(GetRandomLoot());
				m_AirDropLoot.GetInventory().CreateInInventory(GetRandomLoot());
				m_AirDropLoot.GetInventory().CreateInInventory(GetRandomLoot());
				m_AirDropLoot.GetInventory().CreateInInventory(GetRandomLoot());
				m_AirDropLoot.GetInventory().CreateInInventory(GetRandomLoot());
				m_AirDropLoot.GetInventory().CreateInInventory(GetRandomLoot());
				m_AirDropLoot.GetInventory().CreateInInventory(GetRandomLoot());
				m_AirDropLoot.GetInventory().CreateInInventory(GetRandomLoot());
				m_AirDropLoot.GetInventory().CreateInInventory(GetRandomLoot());
				m_AirDropLoot.GetInventory().CreateInInventory(GetRandomLoot());
				m_AirDropLoot.GetInventory().CreateInInventory(GetRandomLoot());
				
				m_AirDropBase = ItemBase.Cast(m_AirDropLoot); // Cast items to airdrop container

				// Play particle when airdrop container, in this case it is red container
				DropEffect = Particle.Play( ParticleList.EXPLOSION_LANDMINE, m_AirDrop.GetPosition() );
			
				if (PrintInformationMessages && !PrintInformationCoordinates)
				SendMessage("[Airdrop] Airdrop landed!");	
				else if (PrintInformationMessages && PrintInformationCoordinates) {
					array<string> arrCoords = new array<string>;
					string strAirdropPos = m_AirDrop.GetPosition().ToString();
					strAirdropPos = strAirdropPos.Substring(1, strAirdropPos.Length() - 2);
					strAirdropPos.Split( ", ", arrCoords );
					SendMessage("Airdrop landed on coordinates at" + Math.Round( arrCoords.Get(0).ToInt() ) + " " + Math.Round( arrCoords.Get(2).ToInt() ) + "!");
				}

				if (SpawnZombie)
				{
					GetGame().CreateObject( WorkingZombieClasses().GetRandomElement(), m_AirDrop.GetPosition() - "10 0 0", false, true );	
					GetGame().CreateObject( WorkingZombieClasses().GetRandomElement(), m_AirDrop.GetPosition() - "0 0 10", false, true );	
					GetGame().CreateObject( WorkingZombieClasses().GetRandomElement(), m_AirDrop.GetPosition() - "10 0 -10", false, true );		
					GetGame().CreateObject( WorkingZombieClasses().GetRandomElement(), m_AirDrop.GetPosition() - "-10 0 10", false, true );
				}
				
				if (ShowSignal)
				{
					vector signal = "0 1.5 0";
					SignalEffect = Particle.Play( ParticleList.RDG2, m_AirDrop.GetPosition() + signal );			
				}

				// Removing physics body
				PhysicsBody.SetPosition(vector.Zero);
				GetGame().ObjectDelete( PhysicsBody ); 
				PhysicsBody = NULL;	
				
				// Reset it to default values
				RayReady = true;
			}
			else
			{
				vector phys;
				phys[0] = m_AirDrop.GetPosition()[0];
				phys[1] = PhysicsBody.GetPosition()[1];
				phys[2] = m_AirDrop.GetPosition()[2];
				
				m_AirDrop.SetPosition(phys);
				m_AirDrop.SetOrientation(PhysicsBody.GetOrientation());
			}
		}

		if (DropTime && !DropOnStart)
		{	
			RayReady = false;

			if (PrintInformationMessages)
			SendMessage("Airdrop was dropped from the plane!");	
			
			m_AirDrop = GetGame().CreateObject( "Land_Container_1Bo", m_DropPos, false, true ); // Create airdrop model, in this case it is red container
			
			SetVelocity(PhysicsBody, "10 0 0");
			GetGame().ObjectDelete(m_Platform);
			SetVelocity(PhysicsBody, "10 0 0");
			
			// Reset it to default values
			RemoveTimer = 0;
			RemovePased = false;
			DropTime = false;		
		}
	}

	/* ### ### ### ### ### ### ### ### */
	/* Airdrop controller */
	/* ### ### ### ### ### ### ### ### */

	bool init = true;
	void CreateAirDrop()
	{
		if (!EnableAirdrops)
			return;

		if (init)
			SendMessage("[Airdrop] Plugin initialized");
		init = false;

		// Remove timer		
		if (RemoveTimer <= RemoveTime)
		{
			RemoveTimer++;
		}
		else
		{
			// Removing all objects when remove timer is passed
			if (!RemovePased)
			{
				if (m_AirDrop != NULL)
				{
					m_AirDrop.SetPosition(vector.Zero);
					GetGame().ObjectDelete( m_AirDrop ); 
					m_AirDrop = NULL;	
				}
				
				if (m_AirPlane != NULL)
				{
					m_AirPlane.SetPosition(vector.Zero);
					GetGame().ObjectDelete( m_AirPlane ); 
					m_AirPlane = NULL;	
				}
				
				if (m_AirDropBase != NULL)
				{
					m_AirDropBase.SetPosition(vector.Zero);
					GetGame().ObjectDelete( m_AirDropBase ); 
					m_AirDropBase = NULL;	
				}
				
				if (m_AirDropLoot != NULL)
				{
					m_AirDropLoot.SetPosition(vector.Zero);
					GetGame().ObjectDelete( m_AirDropLoot ); 
					m_AirDropLoot = NULL;	
				}
				
				if (DropEffect != NULL)
				{
					DropEffect.Stop();
					DropEffect = NULL;
				}
				
				if (SignalEffect != NULL)
				{
					SignalEffect.Stop();
					SignalEffect = NULL;
				}
				
				// Reset it to default values
				AirPassed = false;
				TimerPassed = false;
				AirDropTime = 0;
				AirTimer = 0;	
				DropTime = false;		
				RemovePased = true;	
			}
		}
		
		//  After how much time after restart need to wait before airplane spawn
		if (AirTimer <= TicksTimerFromStart)
		{
			AirTimer++;
			
			if (PrintDebugMessages)
			SendMessage("[Airdrop, Debug] Airtimer value is " + AirTimer);
		}
		else
		{	
			// Reset it to default values
			TimerPassed = true;
		}

		if (TimerPassed && !AirPassed)	
		{
			if (PrintDebugMessages)
			SendMessage("[Airdrop, Debug] Airtimer passed");	
			
			GetAirPlaneInfo();
			
			if (PrintDebugMessages)
			SendMessage("[Airdrop, Debug] Airdrop spawned via timer");		
				
			// Reset it to default values
			AirPassed = true;
		}	

		if (AirPassed)
		{
			if (m_AirPlane)
			{
				MoveAirPlane();
			}
		}
			
		if (AirDropTime <= RandomTime)
		{
			AirDropTime++;
			
			if (TeleportDebug) // For debug puproses only
			{
				SendPos(m_AirPlane.GetPosition());
			}

			if (PrintDebugMessages)
				SendMessage("[Airdrop, Debug] Airdrop time is " + AirDropTime + " from " + RandomTime);		
		}
		else
		{
			if (Delay <= 1000)
			{
				Delay++;
			}
			else
			{
				if (!RayReady)
				{
					if (TeleportDebug) // For debug puproses only
					{
						SendPos(m_AirPlane.GetPosition());
					}
				}
			
				if (!PassTime)
				{
					// Reset it to default values
					DropTime = true;
					PassTime = true;
				}
			}
		}
	}

	/* ### ### ### ### ### ### ### ### */
}
`

and inside my Dayzserver\mpmissions\dayzOffline.chernarusplus\init.c

`class CustomMission: MissionServer
{	

    ref AirDrop AirDropClass; // Class definition

    void CustomMission()
    {
    	AirDropClass = new AirDrop;		
    }
    
    float TimerSlice; // Timeslice
    override void OnUpdate( float timeslice )
    {
    	super.OnUpdate( timeslice );
    
    	// FPS Fix
    	TimerSlice += timeslice;
    	if (TimerSlice >= AirDropClass.TimesliceMultiplyier)
    	{
    		AirDropClass.CreateAirDrop();
    		TimerSlice = 0;	
    	}
    }`

**Comment by S4MT3K** [comment]
Please read the other issues for an "TEMPORALLY FIX"

**Comment by lonewolfss** [comment]
ok that fixed the plane side for me but not the effects but its working well now 💃

**Comment by mov3ax** [comment]
You probably missing something, https://www.youtube.com/watch?v=XENHSLxeix8&feature=youtu.be

**Comment by mov3ax** [comment]
What you have in line 31?

**Comment by S4MT3K** [comment]
Just the class: Class  CustomMission : MissionServer.
Ich changed the order of the code. Now it works!
Don’t know what this is. But its solved. For now!
